@file:Suppress("PackageDirectoryMismatch")

object Versions {

    const val gradleVersion = "7.2.2"
    const val kotlinVersion = "1.7.10"
    const val googleServicesVersion = "4.3.10"
    const val coreKtxVersion = "1.7.0"
    const val appCompatVersion = "1.4.1"
    const val materialVersion = "1.5.0"
    const val constraintLayoutVersion = "2.1.3"
    const val swipeRefreshLayoutVersion = "1.1.0"
    const val junit4Version = "4.13.2"
    const val junitExtensionsVersion = "1.1.3"
    const val espressoCoreVersion = "3.4.0"
    const val daggerHiltVersion = "2.42"
    const val composeNavigationVersion = "2.2.2"
    const val retrofitVersion = "2.9.0"
    const val sandwishVersion = "1.2.2"
    const val okHttpVersion = "4.9.2"
    const val moshiVersion = "1.13.0"
    const val retrofitGson = "2.9.0"
    const val gsonVersion = "2.8.9"
    const val mpAndroidChartVersion = "3.1.0"
    const val lottieVersion = "4.2.0"
    const val truthVersion = "1.1.3"
    const val mockkVersion = "1.12.0"
    const val robolectricVersion = "4.6.1"
    const val androidArchCoreTest = "2.1.0"
    const val coroutinesVersion = "1.6.2"
    const val ktlintVersion = "0.40.0"
    const val roomVersion = "2.4.0"
    const val datastoreVersion = "1.0.0"
    const val picassoVersion = "2.71828"
    const val gradleVersionsPluginVersion = "0.39.0"
    const val composeVersion = "1.0.4"
    const val composeActivityVersion = "1.3.1"
    const val composeViewModelVersion = "2.4.0-rc01"
    const val kotlinCompilerExtensionVersion = "1.1.0-alpha06"
    const val composeConstraintLayoutVersion = "1.0.0-beta02"
    const val hiltNavigationCompose = "1.0.0-alpha03"
    const val accompanistSwipeRefresh = "0.21.0-beta"
    const val navigationComponent = "2.3.5"
    const val animation = "2.4@aar"
    const val linePageIndicator = "1.2.1"
    const val legacy = "1.0.0"
    const val lifeycycleVersion = "2.4.0"
    const val lifeycycleVersion_runtime = "2.4.0-alpha01"
    const val firebaseBomVersion = "29.0.3"
    const val timber_version = "4.7.1"
    const val stdlib_version = "1.5.21"
    const val rxandroid = "3.0.0"
    const val koin = "3.2.0"
    const val rxjava3 = "3.1.3"
    const val rxKotlin = "3.0.1"
    const val glide = "4.12.0"


}
